#!/usr/bin/env bash
# Tests for `gw browser` inside a throwaway $HOME: Chrome profiles, accounts,
# bound repos and gh are all faked. Run: test/browser.sh
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd -P)"
GW="$ROOT/bin/gw"
pass=0 fail=0
ok()   { pass=$((pass + 1)); printf '  ok   %s\n' "$1"; }
bad()  { fail=$((fail + 1)); printf '  FAIL %s\n' "$1"; }
check(){ if [ "$2" = "$3" ]; then ok "$1"; else bad "$1 (want '$3', got '$2')"; fi; }
saw()  { case "$2" in *"$3"*) ok "$1" ;; *) bad "$1" ;; esac; }
nosaw(){ case "$2" in *"$3"*) bad "$1" ;; *) ok "$1" ;; esac; }

TMP="$(cd "$(mktemp -d)" && pwd -P)"
[ -n "$TMP" ] && [ -d "$TMP" ] && [ "$TMP" != / ] || { echo "no temp dir; aborting" >&2; exit 1; }
trap 'rm -rf "$TMP"' EXIT
export HOME="$TMP" GIT_CONFIG_GLOBAL="$TMP/.gitconfig" GIT_CONFIG_NOSYSTEM=1
export GITPLUS_SSH_CONFIG="$TMP/.ssh/config" GITPLUS_GITCONFIG="$TMP/.gitconfig" GITPLUS_SSH_KEY_DIR="$TMP/.ssh"
export GOWORK_CHROME_STATE="$TMP/LocalState" GOWORK_FINICKY_APP="$TMP/Finicky.app" GOWORK_APPS="$TMP/Apps"
: > "$TMP/.gitconfig"; mkdir -p "$TMP/Finicky.app" "$TMP/Apps/Island.app"

cat > "$TMP/LocalState" <<'EOF'
{"profile":{"info_cache":{"Default":{"name":"Personal"},"Profile 3":{"name":"Work"}}}}
EOF

FAKE="$TMP/fakebin"; mkdir -p "$FAKE"
cat > "$FAKE/gh" <<'EOF'
#!/usr/bin/env bash
user=""; prev=""
for a in "$@"; do [ "$prev" = --user ] && user="$a"; prev="$a"; done
case "$1 $2" in
  "auth token") echo "tok-$user"; exit 0 ;;
  "auth status") echo "  - account $(cat "$HOME/active" 2>/dev/null || echo work-gh)"; exit 0 ;;
  "auth refresh"|"auth login") echo "$2 GH_BROWSER=${GH_BROWSER:-}" >> "$HOME/gh-auth"; exit 0 ;;
  "api user/orgs")
    case "$GH_TOKEN" in
      tok-work-gh) printf 'ClientOrg\nshared-org\n' ;;
      tok-me-gh)   printf 'shared-org\n' ;;
    esac; exit 0 ;;
esac
exit 1
EOF
printf '#!/usr/bin/env bash\necho "open $*" >> "%s/opened"\n' "$TMP" > "$FAKE/open"
chmod +x "$FAKE/gh" "$FAKE/open"
export PATH="$FAKE:$PATH"
acct() { "$ROOT/bin/gp-account" "$@" >/dev/null 2>&1; }

acct add work --email w@x.com --gh-user work-gh --dir "$TMP/code/work"
acct add me --email m@x.com --gh-user me-gh --dir "$TMP/code/me"
mkdir -p "$TMP/code/work/app" "$TMP/code/me/tool"
git init -q "$TMP/code/work/app"; git -C "$TMP/code/work/app" remote add origin git@github.com-work:ClientOrg/app.git
git init -q "$TMP/code/me/tool";  git -C "$TMP/code/me/tool" remote add origin https://github.com/me-gh/tool.git
printf '// my own config\nexport default { defaultBrowser: "Safari" };\n' > "$TMP/.finicky.js"

echo "== setup (interactive) =="
if command -v expect >/dev/null 2>&1; then
  expect -c "
    set timeout 10
    spawn $GW browser setup
    expect {signed in to GitHub as work-gh?} { send \"3\r\" }
    expect {signed in to GitHub as me-gh?}   { send \"1\r\" }
    expect {every other link}                { send \"1\r\" }
    expect eof
  " > "$TMP/setup.out" 2>&1
  saw "lists Chrome profiles by name" "$(cat "$TMP/setup.out")" "2) Google Chrome — Work"
  saw "offers other installed browsers whole" "$(cat "$TMP/setup.out")" "3) Island"
  check "account -> browser map saved" "$(cut -f1,2,4 "$TMP/.config/rigor/browser" | tr '\t\n' ':|')" "work:Island:-|me:Google Chrome:Personal|default:Google Chrome:Personal|"
  saw "opens Finicky to become the default" "$(cat "$TMP/opened" 2>/dev/null)" "open -a $TMP/Finicky.app"
else
  echo "  skip interactive setup (no expect)"
  printf 'work\tIsland\t-\t-\nme\tGoogle Chrome\tDefault\tPersonal\ndefault\tGoogle Chrome\tDefault\tPersonal\n' > "$TMP/.config/rigor/browser"
  "$GW" browser sync >/dev/null 2>&1
fi

echo "== generated rules =="
conf="$(cat "$TMP/.finicky.js")"
saw   "marked as gowork's"                 "$conf" "// generated by gowork"
saw   "account's own login routed to its browser" "$conf" '"work-gh": { name: "Island" }'
saw   "org from gh api routed, lowercased" "$conf" '"clientorg": { name: "Island" }'
saw   "personal login to its Chrome profile" "$conf" '"me-gh": { name: "Google Chrome", profile: "Personal" }'
saw   "default set"                        "$conf" 'defaultBrowser: { name: "Google Chrome", profile: "Personal" }'
check "shared org claimed once" "$(grep -c '"shared-org"' "$TMP/.finicky.js")" "1"
saw   "previous config kept"     "$(cat "$TMP/.finicky.js.gowork-bak")" "// my own config"
if command -v node >/dev/null 2>&1; then
  cp "$TMP/.finicky.js" "$TMP/check.mjs"
  node --check "$TMP/check.mjs" 2>/dev/null && ok "generated config is valid JavaScript" || bad "generated config is valid JavaScript"
  # The routing itself, run the way Finicky would.
  cat > "$TMP/route.mjs" <<EOF
import cfg from "$TMP/check.mjs";
const route = (u) => {
  const url = new URL(u), opts = { opener: null };
  for (const h of cfg.handlers) if (h.match(url, opts)) { const b = h.browser(url, opts); return [b.name, b.profile].filter(Boolean).join("/"); }
  return "default";
};
for (const u of ["https://github.com/ClientOrg/app/pull/3", "https://github.com/me-gh/tool", "https://github.com/other/x", "https://example.com/"]) {
  console.log(u, route(u));
}
EOF
  r="$(node "$TMP/route.mjs" 2>&1)"
  saw "client org PR opens in Island" "$r" "ClientOrg/app/pull/3 Island"
  saw "personal repo opens in its Chrome profile" "$r" "me-gh/tool Google Chrome/Personal"
  saw "unknown owner falls to the default" "$r" "github.com/other/x default"
  saw "non-GitHub falls to the default" "$r" "example.com/ default"
else
  echo "  skip JS checks (no node)"
fi

echo "== your own rules =="
"$GW" browser add work '*.sharepoint.com' >/dev/null 2>&1
"$GW" browser add work 'https://jira.example.com/browse/ABC-1?x=1#y' >/dev/null 2>&1
"$GW" browser add me 'jira.example.com/browse/ME' >/dev/null 2>&1
"$GW" browser add work --app Slack >/dev/null 2>&1
out="$("$GW" browser add nobody example.org 2>&1)"; rc=$?
check "rule for an unmapped account is refused" "$rc" "1"
r="$("$GW" browser rules)"
saw "domain rule listed"                 "$r" "*.sharepoint.com"
saw "pasted URL kept as host + path"     "$r" "jira.example.com/browse/ABC-1"
nosaw "query and fragment dropped"       "$r" "?x=1"
saw "app rule listed"                    "$r" "clicked in Slack"
saw "rules show up in the config"        "$(cat "$TMP/.finicky.js")" '{ host: "*.sharepoint.com", path: "", browser: { name: "Island" } }'
if command -v node >/dev/null 2>&1; then
  cp "$TMP/.finicky.js" "$TMP/check2.mjs"
  node --check "$TMP/check2.mjs" 2>/dev/null && ok "config with rules is valid JavaScript" || bad "config with rules is valid JavaScript"
  # Run every handler in order, the way Finicky does, with an opener.
  cat > "$TMP/route2.mjs" <<EOF
import cfg from "$TMP/check2.mjs";
const route = (u, app) => {
  const url = new URL(u), opts = { opener: app ? { name: app, bundleId: "x." + app } : null };
  for (const h of cfg.handlers) if (h.match(url, opts)) { const b = h.browser(url, opts); return [b.name, b.profile].filter(Boolean).join("/"); }
  return "default";
};
for (const [u, app] of [
  ["https://client.sharepoint.com/sites/x", null],
  ["https://sharepoint.com/", null],
  ["https://notsharepoint.com/", null],
  ["https://jira.example.com/browse/ABC-1", null],
  ["https://jira.example.com/browse/ME-2", null],
  ["https://jira.example.com/other", null],
  ["https://news.example.net/", "Slack"],
  ["https://github.com/me-gh/tool", "Slack"],
  ["https://news.example.net/", "Mail"],
]) console.log(u, app || "-", route(u, app));
EOF
  r="$(node "$TMP/route2.mjs" 2>&1)"
  saw "subdomain matches *.domain"         "$r" "client.sharepoint.com/sites/x - Island"
  saw "bare domain matches *.domain too"   "$r" "https://sharepoint.com/ - Island"
  saw "lookalike domain doesn't"           "$r" "https://notsharepoint.com/ - default"
  saw "path prefix rule"                   "$r" "browse/ABC-1 - Island"
  saw "different path, different account" "$r" "browse/ME-2 - Google Chrome/Personal"
  saw "host without a matching path falls through" "$r" "jira.example.com/other - default"
  saw "app rule: clicked in Slack"         "$r" "news.example.net/ Slack Island"
  saw "GitHub owner beats the app rule"    "$r" "me-gh/tool Slack Google Chrome/Personal"
  saw "other apps fall through"            "$r" "news.example.net/ Mail default"
fi
"$GW" browser remove '*.sharepoint.com' >/dev/null 2>&1
"$GW" browser remove --app Slack >/dev/null 2>&1
r="$("$GW" browser rules)"
nosaw "removed domain rule" "$r" "sharepoint"
nosaw "removed app rule" "$r" "Slack"
nosaw "removed from the config" "$(cat "$TMP/.finicky.js")" "sharepoint"
out="$("$GW" browser remove nothing.example 2>&1)"; rc=$?
check "removing a missing rule fails" "$rc" "1"

echo "== gh device logins open in the account's browser =="
# The gh shim first on PATH, the fake gh after it, as `gw account setup` lays them out.
SHIMDIR="$TMP/shim"; mkdir -p "$SHIMDIR"; ln -sf "$ROOT/share/rigor/identity/gh" "$SHIMDIR/gh"
shimgh() { (cd "${2:-$TMP}" && PATH="$SHIMDIR:$PATH" GH_TMP="$TMP" gh auth "$1" >/dev/null 2>&1); }
rm -f "$TMP/gh-auth"; echo work-gh > "$TMP/active"
shimgh refresh
saw "refresh: active account's browser" "$(cat "$TMP/gh-auth")" "refresh GH_BROWSER=$ROOT/libexec/gowork-browser open work-gh"
rm -f "$TMP/gh-auth"
shimgh login "$TMP/code/me/tool"
saw "login: the directory's account" "$(cat "$TMP/gh-auth")" "login GH_BROWSER=$ROOT/libexec/gowork-browser open me-gh"
rm -f "$TMP/gh-auth"
shimgh login "$TMP"
check "login outside any binding: default browser" "$(cat "$TMP/gh-auth")" "login GH_BROWSER="
rm -f "$TMP/gh-auth"
(cd "$TMP" && PATH="$SHIMDIR:$PATH" GH_BROWSER=mine gh auth refresh >/dev/null 2>&1)
check "explicit GH_BROWSER is kept" "$(cat "$TMP/gh-auth")" "refresh GH_BROWSER=mine"
rm -f "$TMP/opened"
GOWORK_OPEN="$FAKE/open" "$GW" browser open work-gh https://github.com/login/device
check "open accepts a gh login for the account" "$(cat "$TMP/opened")" "open -a Island https://github.com/login/device"

echo "== open / status / off =="
rm -f "$TMP/opened"
GOWORK_OPEN="$FAKE/open" "$GW" browser open work https://github.com/settings/keys
check "open goes straight to the account's browser" "$(cat "$TMP/opened")" "open -a Island https://github.com/settings/keys"
rm -f "$TMP/opened"
GOWORK_OPEN="$FAKE/open" "$GW" browser open me https://github.com/settings/keys
check "or to its Chrome profile" "$(cat "$TMP/opened")" "open -na Google Chrome --args --profile-directory=Default https://github.com/settings/keys"
rm -f "$TMP/opened"
GOWORK_OPEN="$FAKE/open" "$GW" browser open nobody https://example.com/
check "unknown account uses the default browser" "$(cat "$TMP/opened")" "open https://example.com/"
saw "status lists the mapping" "$("$GW" browser status 2>&1)" "work           -> Island"
saw "status names Chrome profiles" "$("$GW" browser status 2>&1)" "me             -> Google Chrome — Personal"

# A map written by the first version (account, Chrome profile dir, name) still works.
cp "$TMP/.config/rigor/browser" "$TMP/map.new"
printf 'work\tProfile 3\tWork\n' > "$TMP/.config/rigor/browser"
"$GW" browser sync >/dev/null 2>&1
saw "old three-field map still routes" "$(cat "$TMP/.finicky.js")" '"work-gh": { name: "Google Chrome", profile: "Work" }'
cp "$TMP/map.new" "$TMP/.config/rigor/browser"
"$GW" browser off >/dev/null 2>&1
saw "off restores the previous config" "$(cat "$TMP/.finicky.js")" "// my own config"
[ -f "$TMP/.config/rigor/browser" ] && bad "off forgets the mapping" || ok "off forgets the mapping"
saw "status after off" "$("$GW" browser status 2>&1)" "not set up"

echo ""
echo "$pass passed, $fail failed"
[ "$fail" -eq 0 ]
