#!/usr/bin/env bash
# Tests for `gw browser` inside a throwaway $HOME: Chrome profiles, accounts,
# bound repos and gh are all faked. Run: test/browser.sh
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd -P)"
GW="$ROOT/bin/gw"
pass=0 fail=0
ok()   { pass=$((pass + 1)); printf '  ok   %s\n' "$1"; }
bad()  { fail=$((fail + 1)); printf '  FAIL %s\n' "$1"; }
check(){ if [ "$2" = "$3" ]; then ok "$1"; else bad "$1 (want '$3', got '$2')"; fi; }
saw()  { case "$2" in *"$3"*) ok "$1" ;; *) bad "$1" ;; esac; }
nosaw(){ case "$2" in *"$3"*) bad "$1" ;; *) ok "$1" ;; esac; }

TMP="$(cd "$(mktemp -d)" && pwd -P)"
[ -n "$TMP" ] && [ -d "$TMP" ] && [ "$TMP" != / ] || { echo "no temp dir; aborting" >&2; exit 1; }
trap 'rm -rf "$TMP"' EXIT
export HOME="$TMP" GIT_CONFIG_GLOBAL="$TMP/.gitconfig" GIT_CONFIG_NOSYSTEM=1
export GITPLUS_SSH_CONFIG="$TMP/.ssh/config" GITPLUS_GITCONFIG="$TMP/.gitconfig" GITPLUS_SSH_KEY_DIR="$TMP/.ssh"
export GOWORK_CHROME_STATE="$TMP/LocalState" GOWORK_FINICKY_APP="$TMP/Finicky.app"
: > "$TMP/.gitconfig"; mkdir -p "$TMP/Finicky.app"

cat > "$TMP/LocalState" <<'EOF'
{"profile":{"info_cache":{"Default":{"name":"Personal"},"Profile 3":{"name":"Work"}}}}
EOF

FAKE="$TMP/fakebin"; mkdir -p "$FAKE"
cat > "$FAKE/gh" <<'EOF'
#!/usr/bin/env bash
user=""; prev=""
for a in "$@"; do [ "$prev" = --user ] && user="$a"; prev="$a"; done
case "$1 $2" in
  "auth token") echo "tok-$user"; exit 0 ;;
  "api user/orgs")
    case "$GH_TOKEN" in
      tok-work-gh) printf 'ClientOrg\nshared-org\n' ;;
      tok-me-gh)   printf 'shared-org\n' ;;
    esac; exit 0 ;;
esac
exit 1
EOF
printf '#!/usr/bin/env bash\necho "open $*" >> "%s/opened"\n' "$TMP" > "$FAKE/open"
chmod +x "$FAKE/gh" "$FAKE/open"
export PATH="$FAKE:$PATH"
acct() { "$ROOT/bin/gp-account" "$@" >/dev/null 2>&1; }

acct add work --email w@x.com --gh-user work-gh --dir "$TMP/code/work"
acct add me --email m@x.com --gh-user me-gh --dir "$TMP/code/me"
mkdir -p "$TMP/code/work/app" "$TMP/code/me/tool"
git init -q "$TMP/code/work/app"; git -C "$TMP/code/work/app" remote add origin git@github.com-work:ClientOrg/app.git
git init -q "$TMP/code/me/tool";  git -C "$TMP/code/me/tool" remote add origin https://github.com/me-gh/tool.git
printf '// my own config\nexport default { defaultBrowser: "Safari" };\n' > "$TMP/.finicky.js"

echo "== setup (interactive) =="
if command -v expect >/dev/null 2>&1; then
  expect -c "
    set timeout 10
    spawn $GW browser setup
    expect {signed in to GitHub as work-gh?} { send \"2\r\" }
    expect {signed in to GitHub as me-gh?}   { send \"1\r\" }
    expect {every other link}                { send \"1\r\" }
    expect eof
  " > "$TMP/setup.out" 2>&1
  saw "lists Chrome profiles by name" "$(cat "$TMP/setup.out")" "2) Work"
  check "account -> profile map saved" "$(cut -f1,3 "$TMP/.config/rigor/browser" | tr '\t\n' ':|')" "work:Work|me:Personal|default:Personal|"
  saw "opens Finicky to become the default" "$(cat "$TMP/opened" 2>/dev/null)" "open -a $TMP/Finicky.app"
else
  echo "  skip interactive setup (no expect)"
  printf 'work\tProfile 3\tWork\nme\tDefault\tPersonal\ndefault\tDefault\tPersonal\n' > "$TMP/.config/rigor/browser"
  "$GW" browser sync >/dev/null 2>&1
fi

echo "== generated rules =="
conf="$(cat "$TMP/.finicky.js")"
saw   "marked as gowork's"                 "$conf" "// generated by gowork"
saw   "account's own login routed"         "$conf" '"work-gh": "Work"'
saw   "org from gh api routed, lowercased" "$conf" '"clientorg": "Work"'
saw   "personal login to personal profile" "$conf" '"me-gh": "Personal"'
saw   "default profile set"                "$conf" 'defaultBrowser: chrome("Personal")'
check "shared org claimed once" "$(grep -c '"shared-org"' "$TMP/.finicky.js")" "1"
saw   "previous config kept"     "$(cat "$TMP/.finicky.js.gowork-bak")" "// my own config"
if command -v node >/dev/null 2>&1; then
  cp "$TMP/.finicky.js" "$TMP/check.mjs"
  node --check "$TMP/check.mjs" 2>/dev/null && ok "generated config is valid JavaScript" || bad "generated config is valid JavaScript"
  # The routing itself, run the way Finicky would.
  cat > "$TMP/route.mjs" <<EOF
import cfg from "$TMP/check.mjs";
const h = cfg.handlers[0];
for (const u of ["https://github.com/ClientOrg/app/pull/3", "https://github.com/me-gh/tool", "https://github.com/other/x", "https://example.com/"]) {
  const url = new URL(u);
  console.log(u, h.match(url) ? h.browser(url).profile : "default");
}
EOF
  r="$(node "$TMP/route.mjs" 2>&1)"
  saw "client org PR opens in the work profile" "$r" "ClientOrg/app/pull/3 Work"
  saw "personal repo opens in the personal profile" "$r" "me-gh/tool Personal"
  saw "unknown owner falls to the default" "$r" "github.com/other/x default"
  saw "non-GitHub falls to the default" "$r" "example.com/ default"
else
  echo "  skip JS checks (no node)"
fi

echo "== open / status / off =="
rm -f "$TMP/opened"
GOWORK_OPEN="$FAKE/open" "$GW" browser open work https://github.com/settings/keys
saw "open goes straight to the account's profile" "$(cat "$TMP/opened")" "-na Google Chrome --args --profile-directory=Profile 3 https://github.com/settings/keys"
rm -f "$TMP/opened"
GOWORK_OPEN="$FAKE/open" "$GW" browser open nobody https://example.com/
check "unknown account uses the default browser" "$(cat "$TMP/opened")" "open https://example.com/"
saw "status lists the mapping" "$("$GW" browser status 2>&1)" "work           -> Work"
"$GW" browser off >/dev/null 2>&1
saw "off restores the previous config" "$(cat "$TMP/.finicky.js")" "// my own config"
[ -f "$TMP/.config/rigor/browser" ] && bad "off forgets the mapping" || ok "off forgets the mapping"
saw "status after off" "$("$GW" browser status 2>&1)" "not set up"

echo ""
echo "$pass passed, $fail failed"
[ "$fail" -eq 0 ]
